module.exports = Object.freeze({
  AUTH: 'AUTH',
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_PROFILE: 'SET_PROFILE',
  SET_ITEM_CURRENT: 'SET_ITEM_CURRENT',
  SET_ITEM_LIST: 'SET_ITEM_LIST',
  SET_ITEM_MY_LIST: 'SET_ITEM_MY_LIST',
  NEW_ITEM: 'NEW_ITEM',
  SET_INBOX: 'SET_INBOX',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});
