module.exports = Object.freeze({
    AUTH: 'AUTH',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_PROFILE: 'SET_PROFILE',
    SET_CHAT_MESSAGES: 'SET_CHAT_MESSAGES',
    SET_ITEM_CURRENT: 'SET_ITEM_CURRENT',
    SET_ITEM_LIST: 'SET_ITEM_LIST',
    SET_ITEM_MY_LIST: 'SET_ITEM_MY_LIST',
    NEW_ITEM: 'NEW_ITEM',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
  })
  